---
title: "Tablas COVID-19 por CCAA"
date: "`r Sys.Date()`"

output:
  html_document:
     toc: true
     toc_float: true
  pdf_document: 
     toc: true
---

```{r spin, include=FALSE}
# Este documento permite crear un informe empleando Markdown y `R`.
# Markdown permite la creación de páginas web a partir de documentos de texto de forma muy sencilla 
# (tiene unas reglas sintácticas muy simples) y rápida.
#
# R-Markdown es recomendable para difundir análisis realizados con `R` en distintos formatos.
# Para más detalles ver <http://rmarkdown.rstudio.com> o 
# <https://rubenfcasal.github.io/bookdown_intro/rmarkdown.html>.
#
# Una forma rápida de crear este tipo de informes es emplear la funcion *spin*
# del paquete *knitr* (ver p.e. <http://yihui.name/knitr/demo/stitch> o 
# <https://rubenfcasal.github.io/bookdown_intro/rmarkdown.html#spin>).
#
# Este informe puede ser creado con el siguiente comando:
# library(rmarkdown)
# browseURL(url = render(knitr::spin('COVID-19-tablas.R', knit = FALSE)))
# NOTA: La función `spin` con el parámetro `knit = FALSE` únicamente genera 
# el correspondiente fichero .Rmd (sin generar el informe).
#
# En RStudio es suficiente con seleccionar 'Compile Report' del menú 'File'
# (o pulsar el correspondiente botón de la barra de herramientas).

```
```{r echo=TRUE}
print(load("COVID-19.RData"))

```
```{r results = "asis"}
dates <- names(tables)
for (i in seq_along(files)) {
  cat("\n\n## ", dates[i])
  cat("\n\n File: [", files[i], "](", files[i], ")")
  if (!is.null(tables[[i]])) print(knitr::kable(tables[[i]]))
}
```

