---
output: github_document
params: 
  fecha: "2020-05-21" 
---

# Datos oficiales de COVID-19 en España

<!-- 
Readme.md is generated from Readme.Rmd. 
Please edit that file 

Pendiente:

- Añadir informe datos ISCIII

- Importar y combinar datos datadista

- Añadir enlaces
  
- Combinar tablas MSCBS

-->
El objetivo principal de [este repositorio](https://github.com/rubenfcasal/COVID-19) es facilitar el acceso a los datos del COVID-19 en España a los que pueden estar interesados en analizarlos empleando R. Además se incluye una pequeña recopilación de enlaces a recursos que pueden ser de interés. 

***Nuevo***: El 2020-05-21 se actualizó de nuevo el archivo de datos del ISCIII, después de varios días sin hacerlo, pero no se actualizaron los valores reportados por Cataluña y se eliminó la variable `recuperados`.

***Nota***: Como no paran de cambiar el contenido y el formato de las tablas del informe del *Ministerio de Sanidad, Consumo y Bienestar Social* (MSCBS), no voy a continuar con las actualizaciones de esos datos en este repositorio (no dispongo del tiempo necesario). La recomendación sería utilizar en su lugar por ejemplo los datos en: <https://github.com/datadista/datasets/tree/master/COVID%2019>,
o los datos del ISCIII que continuaré procesando (pese a los comentarios descritos más adelante en las notas...). 
De todos modos continuaré descargándo los informes en pdf.


## Tablas

Las tablas (con un procesado mínimo) están almacenadas en los archivos:

* [acumulados.RData](acumulados.RData) (Fecha actualización: ***`r params$fecha`***): Evolución diaria de casos por CCAA (ISCIII)

* [edadsexo.RData](edadsexo.RData) (Fecha actualización: 2020-04-23): Datos por edad y sexo (MSCBS)

* [COVID-19.RData](COVID-19.RData) (Fecha actualización: 2020-04-23): Datos por CCAA (MSCBS)

En [COVID-19-tablas.html](COVID-19-tablas.html) se muestran las tablas actuales.
En [COVID-19-MSCBS.html](COVID-19-MSCBS.html) se muestran las tablas anteriores del *Ministerio de Sanidad, Consumo y Bienestar Social* (MSCBS) por fecha del informe.
Más adelante se incluyen ***notas importantes*** sobre estos datos y se detallan las fuentes empleadas.


El fichero [acumula2.RData](acumula2.RData) contiene una modificación de los datos del ISCIII en un formato adecuado para el [llamamiento del Comite Español de Matemáticas](http://matematicas.uclm.es/cemat/covid19/2020/04/01/llamamiento-para-compartir-aportaciones-y-poder-crear-un-meta-predictor-a-corto-plazo-basado-en-las-mismas) para la creación de un predictor cooperativo.

* [Web Investigadores UDC (Aplicación Shiny)](https://covid19.citic.udc.es),
  que contiene las predicciones cooperativas (pestaña Predicción cooperativa: Resultados).
  
***Nuevo***: El 2020-05-13 se añadió el directorio *acumula2_hist* que contiene el código necesario para generar el histórico de valores reportados del ISCIII:  [acumula2_hist.RData](acumula2_hist/acumula2_hist.RData), empleado para la evaluación de los predictores. También se genera un informe, [Informe_acumula2_hist.html](acumula2_hist/Informe_acumula2_hist.html), donde se incluyen más detalles (puede servir también para ver algunos de los problemas de los datos reportados por las distintas CCAA en el pasado, pocas se salvan...).
  
***NOTAS acumula2.RData***:  

* El 2020-05-21 se actualizó de nuevo el archivo de datos del ISCIII, después de varios días sin hacerlo, pero no se actualizaron los valores reportados por Cataluña y se eliminó la variable `recuperados`. En este archivo, se les asignó `NA` a los valores del 2020-05-20 de Cataluña y España. 

* El 2020-05-16 no se actualizó el archivo de datos del ISCIII (se les asignó `NA` en este archivo),
pese a que en el informe del ministerio ([Actualizacion_107_COVID-19.pdf](Actualizacion_107_COVID-19.pdf)) todas las CCAA reportaron datos.

<!-- * El 2020-05-08 se vuelven a reportar valores en la variable casos del archivo del ISCIII, que coinciden con los valores de `PCR+`. Sin embargo, por lo menos de momento, se sustituye esta variable por la suma de `PCR+` y `TestAC+` para mantener los valores reportandos anteriormente.
El 2020-05-09 se vuelven a eliminar
-->

* El 2020-04-25 se incluyen dos nuevas variables `PCR+` y `TestAC+` con el número de resultados positivos en pruebas PCR y en test de anticuerpos (se supone que con síntomas) y se reporta `NA` en algunos valores de la variable `Casos` (renombrada como `confirmados` en este archivo) a partir del 2020-04-15.
Aunque en versiones anteriores se suponía que se consideraban confirmados solo los positivos por PCR, aparentemente no es el caso, por lo se sustituyeron estos valores por la suma de `PCR+` y `TestAC+` (desde el 2020-04-28	Galicia ya reporta estas dos variables).

* El 2020-04-22 se recupera la serie histórica de Cataluña (CT) de hospitalizados, uci, fallecidos y recuperados (que se había eliminado desde el 2020-04-17 porque al parecer estaba en revisión por dicha comunidad autónoma),
y se observan cambios en todas las variables respecto a los valores reportados anteriormente. 

* El 2020-04-08 se cambiaron los nombres de las variables del archivo del ISCIII y se cambió el código ISO
de Melilla de `"ME"` a `"ML"`. Sin embargo, por compatibilidad con versiones anteriores el fichero [acumula2.RData](acumula2.RData) mantiene por completo la estructura anterior (incluyendo los niveles del factor `iso`).

* Se incluye una variable `nuevos` a partir del incremento en el número de casos acumulados (aunque realmente no es el número de casos nuevos; ver [nota](https://rubenfcasal.github.io/COVID-19/COVID-19-tablas.html#isciii)) y los totales para España (aunque a día de hoy, esperamos que se solucione pronto, los datos de hospitalización y UCI no son homogéneos entre CCAA; ver comentario más adelante).


***NOTAS datos ISCIII y MSCBS***:

El **2020-05-17** se actualizó de nuevo el archivo de datos del ISCIII (después de no haberlo hecho el día anterior).
Pero Cataluña, Madrid, el País Vasco y Galicia parecen estar haciendo de las suyas. 
Cataluña reporta cada día un número de casos nuevos y posteriormente lo incrementa. 
El País Vasco y aparentemente también Madrid está haciendo algo parecido.
No es serio que a estas alturas no sean capaces de mantener una serie de datos tan básica.

El 2020-05-08 se actualizó la web del ISCIII: <https://cnecovid.isciii.es>, ahora tienen una aplicación Shiny <https://cnecovid.isciii.es/covid19> y los datos pueden descargarse de la pestaña *Documentación y Datos*:  <https://cnecovid.isciii.es/covid19/resources/agregados.csv> (le cambiaron el nombre). Aunque en este repositorio se mantendrá el nombre anterior.

A partir del **2020-04-29** hay un cambio notable en el archivo del ISCIII en los valores reportados por Galicia de UCI (que ahora son acumulados en lugar de prevalencia), fallecidos y recuperados (ver notas más adelante), también disminuye el valor en hospitalizados.

Desde el **2020-04-25** se incluyen en los datos del ISCIII dos nuevas variables `PCR+` y `TestAC+` con el número de resultados positivos en pruebas PCR y en test de anticuerpos (se supone que con síntomas) y se reporta `NA` en algunos valores de la variable `Casos` a partir del 2020-04-15 (no sé muy bien con qué criterio, al principio en varias CCAA y al final solo en Galicia, que no distinguía entre PCR+ y Test+). Desde el 2020-04-28	Galicia ya reporta estas dos variables y la variable `Casos` pasa a ser `NA`. 

Desde el **2020-04-02** se ha venido informando que los valores de hospitalización y UCI reportados por: Castilla-La Mancha (CM), Castilla y León (CL), Comunidad Valenciana (VC), Madrid (MD) y Galicia (GA), son datos de prevalencia (personas ingresadas en la correspondiente fecha) y no reflejan el total de personas que han sido hospitalizadas o ingresadas en UCI a lo largo del periodo de notificación (al contrario de lo que en principio reporta el resto).  
Esto ha ido cambiando a lo largo del tiempo. Desde el 2020-04-28 Galicia ya reporta valores acumulados de UCI (sin embargo sospechamos que ocurre lo mismo con otras CCAA aunque no hasido reportado). Conclusión, por fin parece que empieza a haber **homogeneidad en los datos entre CCAA**. No me lo puedo creer!! (realmente en UCI no me lo creo), que rapidez!!

Por este motivo, **para valores históricos, es preferible recurrir a los datos acumulados del ISCIII**. Aparentemente están tratando de solucionar estos problemas y cuando se produce un cambio en el valor reportado por una CA, tratan de corregir todos los valores anteriores. 
Aunque actualmente no es el caso de muchas CCAA como: Castilla-La Mancha (CM), Castilla y León (CL), Madrid (MD) y Galicia (GA).
Sospechamos también que ha ocurrido lo mismo con otras CCAA, como Andalucía, Extremadura y Baleares que aparentan reportar o haber reportado casos de prevalencia, aunque no se ha informado.
Seguramente hay más errores...

El 2020-04-08 se cambiaron los nombres de las variables del archivo del ISCIII y se cambió el código ISO de Melilla de `"ME"` a `"ML"`. 
Sin embargo, por compatibilidad con versiones anteriores, el fichero [acumulados.RData](acumulados.RData) mantiene los nombres de variables anteriores (aunque con el cambio en el factor `CCAA.ISO`).
En esta fecha también se dejó de calcular el total de España de hospitalizados y UCI en la tabla del MSCBS, se recalculó para mantener la compatibilidad.

Una parte muy pequeña (no para de haber sorpresas con estos datos) de la cronología fue la siguiente (si alguien tiene más información al respecto, le agradecería que me lo comunicase):

* [Actualizacion_63_COVID-19.pdf](Actualizacion_63_COVID-19.pdf) (2020-04-02): Se incluye la primera nota sobre los datos de hospitalizados ("Casos que han precisado hospitalización") de Castilla-La Mancha (CM), Comunidad Valenciana (VC) y Madrid (MD), y UCI ("Casos que han ingresado en UCI") de Madrid (MD). No se aporta ninguna información sobre los datos anteriormente publicados.

* [Actualizacion_64_COVID-19.pdf](Actualizacion_64_COVID-19.pdf) (2020-04-02): Vuelve a aparecer esa nota pero añadiendo, además de los anteriores, los datos de hospitalizados de Castilla y León (CL) y los de UCI de Castilla-La Mancha (CM), Castilla y León (CL), Comunidad Valenciana (VC) y Galicia (GA). 
Al mismo tiempo, al final del archivo que proporciona el ISCIII [serie\_historica\_acumulados.csv](serie_historica_acumulados.csv), se incluye: "Los datos de estas comunidades son datos de prevalencia (personas ingresadas a fecha de hoy) No reflejan el total de personas que han sido hospitalizadas o ingresadas en UCI a lo largo del periodo de notificación (CL-CM-MD-VC-MC)" . Sin embargo, al parecer también ocurre lo mismo con los datos de UCI de Galicia (GA). Murcia (MC) no se menciona en los informes del MSCBS.

* En los siguientes informes se mantiene la misma nota, pero en [Actualizacion_66_COVID-19.pdf](Actualizacion_66_COVID-19.pdf) (2020-04-05) y en la siguiente, no se indica que CCAA son las que aportan datos de prevalencia en hospitalizados o UCI, sin embargo se observa un cambio en Castilla-León en hospitalizados (pasando de 2508 en los datos del 5/4 a 5180 en los del 6/4).

* Posteriormente sigue habiendo cambios, los anotaré cuando tenga tiempo. Desde el 2020-04-28, en principio, todas las comunidades reportan datos homogéneos (aunque desde el 2020-05-10 está habiendo un baile de datos en los casos reportados en Cataluña y Madrid).

Mi opinión personal es que este tipo de problemas, relacionados con unos datos tan básicos,  deberían haberlos solucionado hace mucho tiempo y que (a su debido tiempo) deberían asumir responsabilidades los encargados de los datos de las CCAA y del Ministerio..., parece ser que simplemente cambiaron de criterio algunas CCAA por su cuenta?, por tanto la responsabilidad sería de sus superiores..., no son capaces de entenderse para poner unos datos en común? como mínimo habría que aprender de lo que está pasando de cara a mejorar en el futuro...


***Siguientes pasos***: 

El primero podría ser tratar de conseguir los datos por áreas sanitarias o provincias. 
Esta es la información de la que dispongo:

* Galicia: <https://galiciancovid19.info>

* Castilla y León: <https://analisis.datosabiertos.jcyl.es/pages/coronavirus/descarga-de-datasets#situacin-actual>

* País Vasco: <https://opendata.euskadi.eus/catalogo/-/evolucion-del-coronavirus-covid-19-en-euskadi>

* Andalucía: <https://www.juntadeandalucia.es/institutodeestadisticaycartografia/salud/index.htm>, <https://pakillo.github.io/COVID19-Andalucia/evolucion-coronavirus-andalucia.html>, <https://github.com/Pakillo/COVID19-Andalucia>

* Aragón: <https://opendata.aragon.es/datos/catalogo/dataset/publicaciones-y-anuncios-relacionados-con-el-coronavirus-en-aragon>

* Comunidad Valenciana: <https://dadesobertes.gva.es/va/dataset?q=&sort=views_recent+desc>


También conseguir datos lo más detallados posibles (y fiables) de la evolución en otros lugares, e.g. Corea del Sur, Italia...  

Puedes colaborar a través de GitHub o enviando un correo a [rubenfcasal@gmail.com](mailto:rubenfcasal@gmail.com)

    
## Fuentes de los datos

En un primer momento, al buscar datos oficiales solo encontré esta web del *Ministerio de Sanidad, Consumo y Bienestar Social* (MSCBS): 

https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov-China/situacionActual.htm

donde se puede descargar un pdf con la situación actual (actualizado a las 13:00 durante la semana y a las 12:00 el fin de semana; en la web también hay actualizaciones a otras horas).

Haciendo pruebas, vi que se podían descargar los documentos desde la actualización 31. 
El código y los documentos pdfs los podéis encontrar en este repositorio. 
El archivo `COVID-19-descarga.R` contiene el código necesario para descargar los pdfs.

Posteriormente, gracias a [este comentario](https://hypatia.math.ethz.ch/pipermail/r-help-es/2020-March/013753.html) en la lista de correo de [R-Hispano](http://r-es.org), descubrí otro repositorio que contiene los datos:
https://github.com/datadista/datasets/tree/master/COVID%2019
(de donde pude descargar el fichero `Actualizacion_44_COVID.pdf` que no encontré en la web oficial).

Desde la [Actualizacion_53_COVID-19.pdf](Actualizacion_53_COVID-19.pdf) (2020-03-23) los archivos contienen nuevas tablas con la distribución de casos hospitalizados, ingresados en UCI y fallecidos por grupos de edad y sexo. 
La tabla correspondiente a la última actualización del `r params$fecha` puede consultarse en el listado de tablas [aquí](https://rubenfcasal.github.io/COVID-19/COVID-19-tablas.html#edadsexo).

Desde el **2020-03-26** se pueden descargar los datos oficiales acumulados en la página web [Situación de COVID-19 en España](https://cnecovid.isciii.es/covid19) del [Instituto de Salud Carlos III (ISCIII)](https://www.isciii.es).  
Archivo: [agregados.csv](https://cnecovid.isciii.es/covid19/resources/agregados.csv) 
(también disponible en este repositorio [aquí](agregados.csv);
el archivo [COVID-19-descarga.R](COVID-19-descarga.R) contiene el código necesario para descargar estos datos
y [COVID-19-actualizar.R](COVID-19-actualizar.R) para importarlos a R).
La tabla correspondiente a la última actualización del `r params$fecha` puede consultarse en el listado de tablas [aquí](https://rubenfcasal.github.io/COVID-19/COVID-19-tablas.html#isciii).

De todos modos continuaré manteniendo el historial de datos publicados del MSCBS y los últimos datos por edad y sexo.

Otros enlaces que pueden ser de interés (ver Sección [Enlaces](#enlaces)):

* [Instituto de Salud Carlos III (ISCIII)](https://cnecovid.isciii.es)

    - [Situación de COVID-19 en España](https://cnecovid.isciii.es/covid19)

    - [agregados.csv](https://cnecovid.isciii.es/covid19/resources/agregados.csv)

    - [Informes COVID-19 del Centro Nacional de Epidemiología](https://www.isciii.es/QueHacemos/Servicios/VigilanciaSaludPublicaRENAVE/EnfermedadesTransmisibles/Paginas/InformesCOVID-19.aspx)
    

## Preparación de los datos

### Instalación de los paquetes necesarios

Para extraer las tablas desde R se emplea el paquete [tabulizer](https://docs.ropensci.org/tabulizer),
que depende del paquete [rJava](https://rforge.net/rJava).
Otro paquete que puede ser de utilidad es [pdftools](https://docs.ropensci.org/pdftools), empleado actualmente para extraer las fechas.

Estos dos últimos paquetes se pueden instalar desde CRAN, pero [rJava](https://cran.r-project.org/package=rJava) necesitaría tener instalado previamente el Java Runtime Environment correspondiente al equipo y a la versión de R (e.g [JRE de 64 bits para Windows](https://www.java.com/es/download/windows-64bit.jsp)).

Para instalar [tabulizer](https://docs.ropensci.org/tabulizer) se puede emplear el paquete [devtools](https://devtools.r-lib.org):
```
devtools::install_github( c("ropenscilabs/tabulizerjars", "ropenscilabs/tabulizer"), 
                          INSTALL_opts = "--no-multiarch" )
```

Para instalar el resto de paquetes empleados (puede ser recomendable empezar por aquí) basta con ejecutar en la consola de R:

```
pkgs <- c('rJava', 'pdftools', 'devtools', 'dplyr', 'DT')
install.packages(setdiff(pkgs, installed.packages()[,"Package"]),
                 dependencies = TRUE)

# Si aparecen errores (debidos a incompatibilidades con versiones anteriores de otros paquetes),
# probar a ejecutar en lugar de lo anterior:
# install.packages(pkgs, dependencies = TRUE) # Instala todos...
```

### Extracción

Las tablas por CCAA comienzan en `Actualizacion_35_COVID-19.pdf` (2020-03-03; en la tabla 3, que no se detecta).
Las tablas por CCAA completas comienzan en `Actualizacion_36_COVID-19.pdf` (2020-03-04), 
aunque posteriormente hay cambios en los formatos de las tablas y de los archivos.

Como ya se comentó, a partir de la `Actualizacion_53_COVID-19.pdf` (2020-03-23) están disponibles nuevas tablas con la distribución de casos hospitalizados, ingresados en UCI y fallecidos por grupos de edad y sexo (a partir de los casos notificados que disponían de esa información). También hubo cambios en estas tablas en posteriores informes.

El fichero `COVID-19-procesado.R` contiene el código necesario para extraer de los pdfs las tablas por grupo de edad y sexo (desde `Actualizacion_53_COVID-19.pdf`, 2020-03-23) y las tablas por CCAA (desde `Actualizacion_36_COVID-19.pdf`, 2020-03-04, hasta ¿hoy?).
El fichero [COVID-19-actualizar.R](COVID-19-actualizar.R) contiene el código para la última actualización.


### Tablas

Las tablas (con un procesado mínimo) están almacenadas en los archivos:

-   [edadsexo.RData](edadsexo.RData): Datos por edad y sexo (MSCBS)

-   [acumulados.RData](acumulados.RData): Evolución diaria de casos por CCAA (ISCIII)

-   [COVID-19.RData](COVID-19.RData): Datos por CCAA (MSCBS)

El fichero [COVID-19-tablas.html](COVID-19-tablas.html) contiene un listado (generado automáticamente a partir de [COVID-19-tablas.Rmd](COVID-19-tablas.Rmd)).


## Colabora

Work in progress... ***help needed!***: Especialmente en cuanto al modelado (actualmente está sesgado al campo de la estadística espacio-temporal, debido a la in/experiencia personal...)

El siguiente paso será tratar de conseguir datos por provincias y empezar a ajustar modelos (ver Sección [Enlaces](#enlaces))... 

También puede ser de interés comparar los datos históricos del MSCBS con los del ISCIII (ver nota: "no se puede deducir que la diferencia entre un día y el anterior es el número de casos nuevos ya que esos casos pueden haber sido recuperados de fechas anteriores")...

Si quieres puedes ayudar a través de GitHub o enviando un correo a [rubenfcasal@gmail.com](mailto:rubenfcasal@gmail.com).


## Enlaces

Work in progress... help needed!

* [Acción Matemática contra el Coronavirus](http://matematicas.uclm.es/cemat/covid19)

* [Web Investigadores UDC (Aplicación Shiny)](https://covid19.citic.udc.es),
  que contiene las predicciones cooperativas (pestaña Predicción cooperativa: Resultados).


* Datos CCAA:

    * Galicia: <https://galiciancovid19.info>
    
    * Castilla y León: <https://analisis.datosabiertos.jcyl.es/pages/coronavirus/descarga-de-datasets#situacin-actual>
    
    * País Vasco: <https://opendata.euskadi.eus/catalogo/-/evolucion-del-coronavirus-covid-19-en-euskadi>
    
    * Andalucía: <https://www.juntadeandalucia.es/institutodeestadisticaycartografia/salud/index.htm>, <https://pakillo.github.io/COVID19-Andalucia/evolucion-coronavirus-andalucia.html>, <https://github.com/Pakillo/COVID19-Andalucia>
    
    * Aragón: <https://opendata.aragon.es/datos/catalogo/dataset/publicaciones-y-anuncios-relacionados-con-el-coronavirus-en-aragon>
    
    * Comunidad Valenciana: <https://dadesobertes.gva.es/va/dataset?q=&sort=views_recent+desc>
    

* Pruebas PCR por CCAA: <https://datos.civio.es/dataset/pcr-coronavirus-covid19-espana-comunidades-autonomas>
    
<br>

### COVID-19 y R

* [Top 25 R resources on COVID-19 Coronavirus](https://www.statsandr.com/blog/top-r-resources-on-covid-19-coronavirus)

* [Covid-19 interactive map (using R with shiny, leaflet and dplyr)](http://r-posts.com/covid-19-interactive-map-using-r-with-shiny-leaflet-and-dplyr)

* [COVID-19 epidemiology with R](https://rviews.rstudio.com/2020/03/05/covid-19-epidemiology-with-r)

### Epidemiología (y áreas relacionadas) con R

* https://www.repidemicsconsortium.org

* [Model-based Geostatistics: Methods and Applications in Global Public Health (book)](https://www.crcpress.com/Model-based-Geostatistics-for-Global-Public-Health-Methods-and-Applications/Diggle-Giorgi/p/book/9781138732353) by P.J. Diggle and E. Giorgi (2019),
[código R](https://sites.google.com/site/mbgglobalhealth/r-scripts)

* [Spatio-Temporal Statistics with R (book)](https://spacetimewithr.org) by  C.K. Wikle, A. Zammit-Mangion and N. Cressie (2019), [código R](https://spacetimewithr.org/code) (por si alguien se anima con modelos Bayesianos...)

* [Forecasting: Principles and Practice (book)](https://otexts.com/fpp2), 2ª ed., by R.J. Hyndman and G. Athanasopoulos (2018).

* [Epicalc_Book](https://cran.r-project.org/doc/contrib/Epicalc_Book.pdf)


### Paquetes de R

Paquetes y otras herramientas... 

* [COVID19](https://github.com/emanuele-guidotti/COVID19), [CRAN](https://cran.r-project.org/package=COVID19): Coronavirus COVID-19 (2019-nCoV) Epidemic Datasets

* [cdccovidview](https://cinc.rud.is/web/packages/cdccovidview/): Weekly Surveillance Summary of U.S. COVID-19 Activity

* [coronavirus](https://github.com/RamiKrispin/coronavirus), [CRAN](https://cran.r-project.org/package=coronavirus) : The 2019 Novel Coronavirus COVID-19 (2019-nCoV) Dataset

* [nCov2019](https://github.com/GuangchuangYu/nCov2019): An R package with real-time data, historical data and Shiny app

* [forecast](https://pkg.robjhyndman.com/forecast): Forecasting Functions for Time Series and Linear Models

Se puede realizar una búsqueda en <https://rseek.org>...

